### ISSUE TITLE
Issue templates and license

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-ppa-server#177]
Please add issue templates to this repository. 
I would also suggest that you add the license to the README.md, as done by (nearly) all other CWA repositories ([link](https://github.com/corona-warn-app/cwa-app-ios#licensing) to iOS repo)

Let me know wether a PR reg. this would be welcome.

Best wishes
Tim

**Comment by hilmarf** [comment]
Hi @Ein-Tim,

thanks for your support and suggestion. A PR would be very welcome, if possible please go ahead and create one linked to this ticket.

Thanks a lot!

Regards,
Hilmar

**Comment by Ein-Tim** [comment]
Good evening @hilmarf. 

I opened #180. Happy to hear your feedback
